name: CS2078
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - pytorch::pytorch-cuda=11.8
  - torchvision
  - matplotlib
  - seaborn
  - ipykernel
  - tqdm
